---
services:
  orcaslicer-novnc:
    image: ghcr.io/vajonam/orcaslicer-novnc:local
    build:
      context: .
      args:
        CUDA_IMAGE_TAG: ${CUDA_IMAGE_TAG:-13.0.1-runtime-ubuntu24.04}
        ORCASLICER_VERSION: ${ORCASLICER_VERSION:-latest}
        MEDIA_PROFILE: ${MEDIA_PROFILE:-minimal}
        DEBUG_TOOLS: ${DEBUG_TOOLS:-false}
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - DISPLAY=:0
      - VGL_DISPLAY=egl
      - ORCA_COMPAT_PROFILE=x11-hints
      - ENABLEHWGPU=true
    volumes:
      - ./prints:/prints/
      - ./data:/configs/
    ports:
      - 8080:8080
    restart: unless-stopped
