[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid

[program:vnc]
priority=0
command=/bin/bash -lc 'exec env -u __GLX_VENDOR_LIBRARY_NAME -u __EGL_VENDOR_LIBRARY_FILENAMES /opt/TurboVNC/bin/vncserver %(ENV_DISPLAY)s -xstartup /etc/turbovnc-xstartup.sh -fg %(ENV_VNC_SEC)s -depth 24 -geometry %(ENV_VNC_RESOLUTION)s -desktop "Orcaslicer" -extension GLX'
autorestart=true
redirect_stderr=true

[program:novnc]
priority=0
command=websockify --web=/usr/share/novnc/ %(ENV_NOVNC_PORT)s  localhost:%(ENV_LOCALFBPORT)s
autorestart=true
redirect_stderr=true

[program:orcaslicer]
priority=1
environment=DISPLAY="%(ENV_DISPLAY)s",VGL_DISPLAY="%(ENV_VGL_DISPLAY)s",NO_AT_BRIDGE="1",GDK_BACKEND="x11",GDK_SCALE="1",GDK_DPI_SCALE="1",GTK_THEME="%(ENV_ORCA_GTK_THEME)s",XDG_SESSION_TYPE="%(ENV_ORCA_XDG_SESSION_TYPE)s",XDG_CURRENT_DESKTOP="%(ENV_ORCA_XDG_CURRENT_DESKTOP)s",XDG_SESSION_DESKTOP="%(ENV_ORCA_XDG_SESSION_DESKTOP)s",GTK_CSD="%(ENV_ORCA_GTK_CSD)s",GDK_DISABLE="%(ENV_ORCA_GDK_DISABLE)s",DBUS_SESSION_BUS_ADDRESS="%(ENV_ORCA_DBUS_SESSION_BUS_ADDRESS)s",__GLX_VENDOR_LIBRARY_NAME="nvidia",__EGL_VENDOR_LIBRARY_FILENAMES="/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
command=/bin/bash -lc 'sleep 2; if [ -n "%(ENV_VGLRUN)s" ]; then exec %(ENV_VGLRUN)s /slic3r/squashfs-root/AppRun --datadir /home/slic3r/.config/OrcaSlicer/; else exec /slic3r/squashfs-root/AppRun --datadir /home/slic3r/.config/OrcaSlicer/; fi'
autorestart=true
redirect_stderr=true
