[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid

[program:vnc]
priority=0
command=/bin/bash -lc 'exec env -u __GLX_VENDOR_LIBRARY_NAME -u __EGL_VENDOR_LIBRARY_FILENAMES /opt/TurboVNC/bin/vncserver %(ENV_DISPLAY)s -xstartup /etc/turbovnc-xstartup.sh -fg %(ENV_VNC_SEC)s -depth 24 -geometry %(ENV_VNC_RESOLUTION)s -desktop "Orcaslicer" -extension GLX'
autorestart=true
redirect_stderr=true

[program:novnc]
priority=0
command=websockify --web=/usr/share/novnc/ %(ENV_NOVNC_PORT)s  localhost:%(ENV_LOCALFBPORT)s
autorestart=true
redirect_stderr=true

[program:orcaslicer]
priority=1
environment=DISPLAY=%(ENV_DISPLAY)s,VGL_DISPLAY=%(ENV_VGL_DISPLAY)s,NO_AT_BRIDGE=1,GDK_BACKEND=x11,GDK_SCALE=1,GDK_DPI_SCALE=1,GTK_THEME=Adwaita,__GLX_VENDOR_LIBRARY_NAME=nvidia,__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
command=/bin/bash -lc 'sleep 2; if [ -n "%(ENV_VGLRUN)s" ]; then exec %(ENV_VGLRUN)s /slic3r/squashfs-root/AppRun --datadir /configs/.config/OrcaSlicer/; else exec /slic3r/squashfs-root/AppRun --datadir /configs/.config/OrcaSlicer/; fi'
autorestart=true
redirect_stderr=true
