name: Tag latest

on:
  schedule:
    - cron: "0 1 * * *" # Daily check
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (orcaslicer branch)
        uses: actions/checkout@v4
        with:
          ref: orcaslicer
          fetch-depth: 0

      - name: Tag the latest Orcaslicer if available
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./tag_latest_orcaslicer.sh
          ./tag_latest_orcaslicer.sh
